### ISSUE TITLE
Bug: SQLSTATE[HY000]: General error: 1005 Can't create table `laravel`.`pedidos` (errno: 150 "Foreign key constraint is incorrectly formed")

### ISSUE THREAD

**Issue by ReinanHS** [rayssasandrade/CRUDProduto#1]
## Resumo

Está ocorrendo um erro ao criar as tabelas no banco de dados

## Passos para reproduzir

Para reproduzir o problema, o desenvolvedor deve usar o comando `php artisan migrate`

## Qual é o comportamento do bug atual?

`
SQLSTATE[HY000]: General error: 1005 Can't create table `laravel`.`pedidos` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `pedidos` add constraint `pedidos_cliente
_id_foreign` foreign key (`cliente_id`) references `users` (`id`))
`

## Qual é o comportamento correto esperado?

O comando deve criar todas as tabelas sem erros.

## Registros e / ou capturas de tela relevantes

![image](https://user-images.githubusercontent.com/28494067/130638507-dfaf7360-516f-4941-be91-ebb4af64edda.png)

**Comment by rayssasandrade** [comment]
resolvido
